// Code generated by MockGen. DO NOT EDIT.
// Source: proposal_sync_state.go
//
// Generated by this command:
//
//	mockgen -source=proposal_sync_state.go -destination=proposal_sync_state_mock.go -package=inter
//

// Package inter is a generated GoMock package.
package inter

import (
	reflect "reflect"

	hash "github.com/Fantom-foundation/lachesis-base/hash"
	idx "github.com/Fantom-foundation/lachesis-base/inter/idx"
	gomock "go.uber.org/mock/gomock"
)

// MockEventReader is a mock of EventReader interface.
type MockEventReader struct {
	ctrl     *gomock.Controller
	recorder *MockEventReaderMockRecorder
}

// MockEventReaderMockRecorder is the mock recorder for MockEventReader.
type MockEventReaderMockRecorder struct {
	mock *MockEventReader
}

// NewMockEventReader creates a new mock instance.
func NewMockEventReader(ctrl *gomock.Controller) *MockEventReader {
	mock := &MockEventReader{ctrl: ctrl}
	mock.recorder = &MockEventReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventReader) EXPECT() *MockEventReaderMockRecorder {
	return m.recorder
}

// GetEpochStartBlock mocks base method.
func (m *MockEventReader) GetEpochStartBlock(arg0 idx.Epoch) idx.Block {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochStartBlock", arg0)
	ret0, _ := ret[0].(idx.Block)
	return ret0
}

// GetEpochStartBlock indicates an expected call of GetEpochStartBlock.
func (mr *MockEventReaderMockRecorder) GetEpochStartBlock(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochStartBlock", reflect.TypeOf((*MockEventReader)(nil).GetEpochStartBlock), arg0)
}

// GetEventPayload mocks base method.
func (m *MockEventReader) GetEventPayload(arg0 hash.Event) Payload {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventPayload", arg0)
	ret0, _ := ret[0].(Payload)
	return ret0
}

// GetEventPayload indicates an expected call of GetEventPayload.
func (mr *MockEventReaderMockRecorder) GetEventPayload(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventPayload", reflect.TypeOf((*MockEventReader)(nil).GetEventPayload), arg0)
}
