// Code generated by MockGen. DO NOT EDIT.
// Source: gas_power_check.go
//
// Generated by this command:
//
//	mockgen -source=gas_power_check.go -destination=gas_power_check_mock.go -package=gaspowercheck
//

// Package gaspowercheck is a generated GoMock package.
package gaspowercheck

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// GetValidationContext mocks base method.
func (m *MockReader) GetValidationContext() *ValidationContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidationContext")
	ret0, _ := ret[0].(*ValidationContext)
	return ret0
}

// GetValidationContext indicates an expected call of GetValidationContext.
func (mr *MockReaderMockRecorder) GetValidationContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidationContext", reflect.TypeOf((*MockReader)(nil).GetValidationContext))
}
