version: "2"
linters:
  settings:
    staticcheck:
      checks:
        # Ignore specific checks to be fixed.
        - "-ST1000" # Incorrect or missing package comment.
        - "-ST1003" # Poorly chosen identifier.
        - "-ST1005" # Incorrectly formatted error string.
        - "-ST1016" # Use consistent method receiver names.
        - "-ST1020" # The documentation of an exported function should start with the function's name.
        - "-ST1021" # The documentation of an exported type should start with type's name.
        - "-ST1022" # The documentation of an exported variable or constant should start with variable's name.
        - "-ST1023" # Redundant type in variable declaration.
        - "-QF1001" # Apply De Morgan's law.
        - "-QF1002" # Convert untagged switch to tagged switch.
        - "-QF1003" # Convert if/else-if chain to tagged switch.
        - "-QF1006" # Lift 'if'+'break' into loop condition.
        - "-QF1008" # Omit embedded fields from selector expression.
        - "-QF1011" # Omit redundant type from variable declaration.
        - "-SA1019" # Using a deprecated function, variable, constant or field.


formatters:
  # Enable specific formatter.
  enable:
    # - gofmt # enable once https://github.com/0xsoniclabs/sonic/pull/225 is merged

issues:
  # do not limit number of findings per linter
  max-issues-per-linter: 0
  # do not limit number of same finding
  max-same-issues: 0
  # do not limit number of issues per line
  uniq-by-line: false

output:
  formats:
    text:
      path: ./golangci-lint-report.txt
    html:
      path: ./golangci-lint-report.html