// Copyright 2025 Sonic Operations Ltd
// This file is part of the Sonic Client
//
// Sonic is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Sonic is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Sonic. If not, see <http://www.gnu.org/licenses/>.

// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -package=gossip -destination=service_mock.go
//

// Package gossip is a generated GoMock package.
package gossip

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockArchiveBlockHeightSource is a mock of ArchiveBlockHeightSource interface.
type MockArchiveBlockHeightSource struct {
	ctrl     *gomock.Controller
	recorder *MockArchiveBlockHeightSourceMockRecorder
	isgomock struct{}
}

// MockArchiveBlockHeightSourceMockRecorder is the mock recorder for MockArchiveBlockHeightSource.
type MockArchiveBlockHeightSourceMockRecorder struct {
	mock *MockArchiveBlockHeightSource
}

// NewMockArchiveBlockHeightSource creates a new mock instance.
func NewMockArchiveBlockHeightSource(ctrl *gomock.Controller) *MockArchiveBlockHeightSource {
	mock := &MockArchiveBlockHeightSource{ctrl: ctrl}
	mock.recorder = &MockArchiveBlockHeightSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArchiveBlockHeightSource) EXPECT() *MockArchiveBlockHeightSourceMockRecorder {
	return m.recorder
}

// GetArchiveBlockHeight mocks base method.
func (m *MockArchiveBlockHeightSource) GetArchiveBlockHeight() (uint64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchiveBlockHeight")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetArchiveBlockHeight indicates an expected call of GetArchiveBlockHeight.
func (mr *MockArchiveBlockHeightSourceMockRecorder) GetArchiveBlockHeight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchiveBlockHeight", reflect.TypeOf((*MockArchiveBlockHeightSource)(nil).GetArchiveBlockHeight))
}
