// Copyright 2025 Sonic Operations Ltd
// This file is part of the Sonic Client
//
// Sonic is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Sonic is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Sonic. If not, see <http://www.gnu.org/licenses/>.

// Code generated by MockGen. DO NOT EDIT.
// Source: evm.go
//
// Generated by this command:
//
//	mockgen -source=evm.go -destination=evm_mock.go -package=evmcore
//

// Package evmcore is a generated GoMock package.
package evmcore

import (
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockDummyChain is a mock of DummyChain interface.
type MockDummyChain struct {
	ctrl     *gomock.Controller
	recorder *MockDummyChainMockRecorder
}

// MockDummyChainMockRecorder is the mock recorder for MockDummyChain.
type MockDummyChainMockRecorder struct {
	mock *MockDummyChain
}

// NewMockDummyChain creates a new mock instance.
func NewMockDummyChain(ctrl *gomock.Controller) *MockDummyChain {
	mock := &MockDummyChain{ctrl: ctrl}
	mock.recorder = &MockDummyChainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDummyChain) EXPECT() *MockDummyChainMockRecorder {
	return m.recorder
}

// GetHeader mocks base method.
func (m *MockDummyChain) GetHeader(arg0 common.Hash, arg1 uint64) *EvmHeader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeader", arg0, arg1)
	ret0, _ := ret[0].(*EvmHeader)
	return ret0
}

// GetHeader indicates an expected call of GetHeader.
func (mr *MockDummyChainMockRecorder) GetHeader(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeader", reflect.TypeOf((*MockDummyChain)(nil).GetHeader), arg0, arg1)
}
