// Code generated by MockGen. DO NOT EDIT.
// Source: evm.go
//
// Generated by this command:
//
//	mockgen -source=evm.go -destination=evm_mock.go -package=evmcore
//

// Package evmcore is a generated GoMock package.
package evmcore

import (
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockDummyChain is a mock of DummyChain interface.
type MockDummyChain struct {
	ctrl     *gomock.Controller
	recorder *MockDummyChainMockRecorder
}

// MockDummyChainMockRecorder is the mock recorder for MockDummyChain.
type MockDummyChainMockRecorder struct {
	mock *MockDummyChain
}

// NewMockDummyChain creates a new mock instance.
func NewMockDummyChain(ctrl *gomock.Controller) *MockDummyChain {
	mock := &MockDummyChain{ctrl: ctrl}
	mock.recorder = &MockDummyChainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDummyChain) EXPECT() *MockDummyChainMockRecorder {
	return m.recorder
}

// GetHeader mocks base method.
func (m *MockDummyChain) GetHeader(arg0 common.Hash, arg1 uint64) *EvmHeader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeader", arg0, arg1)
	ret0, _ := ret[0].(*EvmHeader)
	return ret0
}

// GetHeader indicates an expected call of GetHeader.
func (mr *MockDummyChainMockRecorder) GetHeader(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeader", reflect.TypeOf((*MockDummyChain)(nil).GetHeader), arg0, arg1)
}
