// Code generated by MockGen. DO NOT EDIT.
// Source: subsidies_integration.go
//
// Generated by this command:
//
//	mockgen -source=subsidies_integration.go -destination=subsidies_integration_mock.go -package=evmcore
//

// Package evmcore is a generated GoMock package.
package evmcore

import (
	reflect "reflect"

	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MocksubsidiesChecker is a mock of subsidiesChecker interface.
type MocksubsidiesChecker struct {
	ctrl     *gomock.Controller
	recorder *MocksubsidiesCheckerMockRecorder
	isgomock struct{}
}

// MocksubsidiesCheckerMockRecorder is the mock recorder for MocksubsidiesChecker.
type MocksubsidiesCheckerMockRecorder struct {
	mock *MocksubsidiesChecker
}

// NewMocksubsidiesChecker creates a new mock instance.
func NewMocksubsidiesChecker(ctrl *gomock.Controller) *MocksubsidiesChecker {
	mock := &MocksubsidiesChecker{ctrl: ctrl}
	mock.recorder = &MocksubsidiesCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksubsidiesChecker) EXPECT() *MocksubsidiesCheckerMockRecorder {
	return m.recorder
}

// isSponsored mocks base method.
func (m *MocksubsidiesChecker) isSponsored(tx *types.Transaction) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "isSponsored", tx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// isSponsored indicates an expected call of isSponsored.
func (mr *MocksubsidiesCheckerMockRecorder) isSponsored(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isSponsored", reflect.TypeOf((*MocksubsidiesChecker)(nil).isSponsored), tx)
}
