// Code generated by MockGen. DO NOT EDIT.
// Source: state.go
//
// Generated by this command:
//
//	mockgen -source=state.go -destination=state_mock.go -package=node
//

// Package node is a generated GoMock package.
package node

import (
	reflect "reflect"

	scc "github.com/0xsoniclabs/sonic/scc"
	gomock "go.uber.org/mock/gomock"
)

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// GetCurrentCommittee mocks base method.
func (m *MockState) GetCurrentCommittee() scc.Committee {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentCommittee")
	ret0, _ := ret[0].(scc.Committee)
	return ret0
}

// GetCurrentCommittee indicates an expected call of GetCurrentCommittee.
func (mr *MockStateMockRecorder) GetCurrentCommittee() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentCommittee", reflect.TypeOf((*MockState)(nil).GetCurrentCommittee))
}
