// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=store_mock.go -package=node
//

// Package node is a generated GoMock package.
package node

import (
	"github.com/0xsoniclabs/consensus/consensus"
	reflect "reflect"

	scc "github.com/0xsoniclabs/sonic/scc"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetBlockCertificate mocks base method.
func (m *MockStore) GetBlockCertificate(arg0 consensus.BlockID) (BlockCertificate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockCertificate", arg0)
	ret0, _ := ret[0].(BlockCertificate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockCertificate indicates an expected call of GetBlockCertificate.
func (mr *MockStoreMockRecorder) GetBlockCertificate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockCertificate", reflect.TypeOf((*MockStore)(nil).GetBlockCertificate), arg0)
}

// GetCommitteeCertificate mocks base method.
func (m *MockStore) GetCommitteeCertificate(arg0 scc.Period) (CommitteeCertificate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitteeCertificate", arg0)
	ret0, _ := ret[0].(CommitteeCertificate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitteeCertificate indicates an expected call of GetCommitteeCertificate.
func (mr *MockStoreMockRecorder) GetCommitteeCertificate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitteeCertificate", reflect.TypeOf((*MockStore)(nil).GetCommitteeCertificate), arg0)
}

// UpdateBlockCertificate mocks base method.
func (m *MockStore) UpdateBlockCertificate(arg0 BlockCertificate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockCertificate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBlockCertificate indicates an expected call of UpdateBlockCertificate.
func (mr *MockStoreMockRecorder) UpdateBlockCertificate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockCertificate", reflect.TypeOf((*MockStore)(nil).UpdateBlockCertificate), arg0)
}

// UpdateCommitteeCertificate mocks base method.
func (m *MockStore) UpdateCommitteeCertificate(arg0 CommitteeCertificate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommitteeCertificate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCommitteeCertificate indicates an expected call of UpdateCommitteeCertificate.
func (mr *MockStoreMockRecorder) UpdateCommitteeCertificate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommitteeCertificate", reflect.TypeOf((*MockStore)(nil).UpdateCommitteeCertificate), arg0)
}
