// Code generated by MockGen. DO NOT EDIT.
// Source: subsidies.go
//
// Generated by this command:
//
//	mockgen -source=subsidies.go -destination=subsidies_mock.go -package=subsidies
//

// Package subsidies is a generated GoMock package.
package subsidies

import (
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	uint256 "github.com/holiman/uint256"
	gomock "go.uber.org/mock/gomock"
)

// MockVirtualMachine is a mock of VirtualMachine interface.
type MockVirtualMachine struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualMachineMockRecorder
	isgomock struct{}
}

// MockVirtualMachineMockRecorder is the mock recorder for MockVirtualMachine.
type MockVirtualMachineMockRecorder struct {
	mock *MockVirtualMachine
}

// NewMockVirtualMachine creates a new mock instance.
func NewMockVirtualMachine(ctrl *gomock.Controller) *MockVirtualMachine {
	mock := &MockVirtualMachine{ctrl: ctrl}
	mock.recorder = &MockVirtualMachineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualMachine) EXPECT() *MockVirtualMachineMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockVirtualMachine) Call(from, to common.Address, input []byte, gas uint64, value *uint256.Int) ([]byte, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", from, to, input, gas, value)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Call indicates an expected call of Call.
func (mr *MockVirtualMachineMockRecorder) Call(from, to, input, gas, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockVirtualMachine)(nil).Call), from, to, input, gas, value)
}

// MockNonceSource is a mock of NonceSource interface.
type MockNonceSource struct {
	ctrl     *gomock.Controller
	recorder *MockNonceSourceMockRecorder
	isgomock struct{}
}

// MockNonceSourceMockRecorder is the mock recorder for MockNonceSource.
type MockNonceSourceMockRecorder struct {
	mock *MockNonceSource
}

// NewMockNonceSource creates a new mock instance.
func NewMockNonceSource(ctrl *gomock.Controller) *MockNonceSource {
	mock := &MockNonceSource{ctrl: ctrl}
	mock.recorder = &MockNonceSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNonceSource) EXPECT() *MockNonceSourceMockRecorder {
	return m.recorder
}

// GetNonce mocks base method.
func (m *MockNonceSource) GetNonce(addr common.Address) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNonce", addr)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetNonce indicates an expected call of GetNonce.
func (mr *MockNonceSourceMockRecorder) GetNonce(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNonce", reflect.TypeOf((*MockNonceSource)(nil).GetNonce), addr)
}

// MockSenderReader is a mock of SenderReader interface.
type MockSenderReader struct {
	ctrl     *gomock.Controller
	recorder *MockSenderReaderMockRecorder
	isgomock struct{}
}

// MockSenderReaderMockRecorder is the mock recorder for MockSenderReader.
type MockSenderReaderMockRecorder struct {
	mock *MockSenderReader
}

// NewMockSenderReader creates a new mock instance.
func NewMockSenderReader(ctrl *gomock.Controller) *MockSenderReader {
	mock := &MockSenderReader{ctrl: ctrl}
	mock.recorder = &MockSenderReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSenderReader) EXPECT() *MockSenderReaderMockRecorder {
	return m.recorder
}

// Sender mocks base method.
func (m *MockSenderReader) Sender(arg0 *types.Transaction) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sender", arg0)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sender indicates an expected call of Sender.
func (mr *MockSenderReaderMockRecorder) Sender(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sender", reflect.TypeOf((*MockSenderReader)(nil).Sender), arg0)
}
