// Code generated by "stringer -type=Feature"; DO NOT EDIT.

package opera

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NilFeature-0]
	_ = x[SingleProposerProtocol-1]
}

const _Feature_name = "NilFeatureSingleProposerProtocol"

var _Feature_index = [...]uint8{0, 10, 32}

func (i Feature) String() string {
	if i >= Feature(len(_Feature_index)-1) {
		return "Feature(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Feature_name[_Feature_index[i]:_Feature_index[i+1]]
}
