// prevrandao package provides the functionality
// to generate the prevrandao value for the sonic consensus
// protocol.
package randao

import (
	"crypto/sha256"

	"github.com/0xsoniclabs/sonic/inter/validatorpk"
	"github.com/0xsoniclabs/sonic/valkeystore"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
)

// RandaoReveal is an opaque object that can be used by peers to generate
// the same randao value.
// RandaoReveal is generated by one node (proposer), the generation algorithm
// can then be reproduced by other nodes, verifying it.
type RandaoReveal []byte

// NewRandaoReveal Constructs a new RandaoReveal
//   - previousRandAo is the previous randao value
//   - proposerKey is the public key of the proposer originating this randao value
//   - Signer is the signer used to sign messages within the gossip package
func NewRandaoReveal(
	previousRandAo common.Hash,
	proposerKey validatorpk.PubKey,
	Signer valkeystore.SignerI,
) (RandaoReveal, error) {
	hash := sha256.Sum256(previousRandAo[:])
	return Signer.Sign(proposerKey, hash[:])
}

// GetRandAo verifies randaoSource payload and generates a new randao value.
// If the verification can be proven, this value is equal on all peers.
//   - previousRandAo is the previous randao value
//   - proposerKey is the public key of the proposer originating this randao value
func (s RandaoReveal) GetRandAo(
	previousRandAo common.Hash,
	proposerPublicKey validatorpk.PubKey,
) (common.Hash, bool) {

	hash := sha256.Sum256(previousRandAo[:])

	// if the signature does not correspond to the input data (hash, replayProtection)
	// for the given proposerPublicKey, then randao cannot be generated.
	if ok := crypto.VerifySignature(proposerPublicKey.Raw, hash[:], s); !ok {
		return common.Hash{}, false
	}

	// next randao is the hash of the reveal
	return sha256.Sum256(s), true
}
