// Copyright 2025 Sonic Operations Ltd
// This file is part of the Sonic Client
//
// Sonic is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Sonic is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Sonic. If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: block_certificate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A certificate proofing the validity of block meta information.
type BlockCertificate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The aggregated signature of the certification committee active during the
	// block's creation, certifying the block's meta information.
	Signature *AggregatedSignature `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// The chain ID of the chain the block is part of.
	ChainId uint64 `protobuf:"varint,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	// The block number.
	Number uint64 `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	// The 32-byte hash of the block.
	Hash []byte `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	// The 32-byte hash of the state root of the block.
	StateRoot     []byte `protobuf:"bytes,5,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCertificate) Reset() {
	*x = BlockCertificate{}
	mi := &file_block_certificate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCertificate) ProtoMessage() {}

func (x *BlockCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_block_certificate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCertificate.ProtoReflect.Descriptor instead.
func (*BlockCertificate) Descriptor() ([]byte, []int) {
	return file_block_certificate_proto_rawDescGZIP(), []int{0}
}

func (x *BlockCertificate) GetSignature() *AggregatedSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *BlockCertificate) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *BlockCertificate) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BlockCertificate) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BlockCertificate) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

var File_block_certificate_proto protoreflect.FileDescriptor

const file_block_certificate_proto_rawDesc = "" +
	"\n" +
	"\x17block_certificate.proto\x12\x14sonic.scc.cert.proto\x1a\x0fsignature.proto\"\xbf\x01\n" +
	"\x10BlockCertificate\x12G\n" +
	"\tsignature\x18\x01 \x01(\v2).sonic.scc.cert.proto.AggregatedSignatureR\tsignature\x12\x18\n" +
	"\achainId\x18\x02 \x01(\x04R\achainId\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x04R\x06number\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\fR\x04hash\x12\x1c\n" +
	"\tstateRoot\x18\x05 \x01(\fR\tstateRootB\x06Z\x04.;pbb\x06proto3"

var (
	file_block_certificate_proto_rawDescOnce sync.Once
	file_block_certificate_proto_rawDescData []byte
)

func file_block_certificate_proto_rawDescGZIP() []byte {
	file_block_certificate_proto_rawDescOnce.Do(func() {
		file_block_certificate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_certificate_proto_rawDesc), len(file_block_certificate_proto_rawDesc)))
	})
	return file_block_certificate_proto_rawDescData
}

var file_block_certificate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_block_certificate_proto_goTypes = []any{
	(*BlockCertificate)(nil),    // 0: sonic.scc.cert.proto.BlockCertificate
	(*AggregatedSignature)(nil), // 1: sonic.scc.cert.proto.AggregatedSignature
}
var file_block_certificate_proto_depIdxs = []int32{
	1, // 0: sonic.scc.cert.proto.BlockCertificate.signature:type_name -> sonic.scc.cert.proto.AggregatedSignature
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_block_certificate_proto_init() }
func file_block_certificate_proto_init() {
	if File_block_certificate_proto != nil {
		return
	}
	file_signature_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_certificate_proto_rawDesc), len(file_block_certificate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_certificate_proto_goTypes,
		DependencyIndexes: file_block_certificate_proto_depIdxs,
		MessageInfos:      file_block_certificate_proto_msgTypes,
	}.Build()
	File_block_certificate_proto = out.File
	file_block_certificate_proto_goTypes = nil
	file_block_certificate_proto_depIdxs = nil
}
