// Copyright 2025 Sonic Operations Ltd
// This file is part of the Sonic Client
//
// Sonic is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Sonic is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Sonic. If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: signature.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The aggregated signature of multiple signers.
type AggregatedSignature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The 96-byte BLS signature aggregating the signatures of all signers.
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// A bit-mask indicating which signers have signed the block.
	// The i-th bit of the mask corresponds to the i-th signer.
	// If the i-th bit is set, the i-th signer has signed the block.
	SignerMask    []byte `protobuf:"bytes,2,opt,name=signerMask,proto3" json:"signerMask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedSignature) Reset() {
	*x = AggregatedSignature{}
	mi := &file_signature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedSignature) ProtoMessage() {}

func (x *AggregatedSignature) ProtoReflect() protoreflect.Message {
	mi := &file_signature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedSignature.ProtoReflect.Descriptor instead.
func (*AggregatedSignature) Descriptor() ([]byte, []int) {
	return file_signature_proto_rawDescGZIP(), []int{0}
}

func (x *AggregatedSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AggregatedSignature) GetSignerMask() []byte {
	if x != nil {
		return x.SignerMask
	}
	return nil
}

var File_signature_proto protoreflect.FileDescriptor

const file_signature_proto_rawDesc = "" +
	"\n" +
	"\x0fsignature.proto\x12\x14sonic.scc.cert.proto\"S\n" +
	"\x13AggregatedSignature\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x1e\n" +
	"\n" +
	"signerMask\x18\x02 \x01(\fR\n" +
	"signerMaskB\x06Z\x04.;pbb\x06proto3"

var (
	file_signature_proto_rawDescOnce sync.Once
	file_signature_proto_rawDescData []byte
)

func file_signature_proto_rawDescGZIP() []byte {
	file_signature_proto_rawDescOnce.Do(func() {
		file_signature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signature_proto_rawDesc), len(file_signature_proto_rawDesc)))
	})
	return file_signature_proto_rawDescData
}

var file_signature_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_signature_proto_goTypes = []any{
	(*AggregatedSignature)(nil), // 0: sonic.scc.cert.proto.AggregatedSignature
}
var file_signature_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_signature_proto_init() }
func file_signature_proto_init() {
	if File_signature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signature_proto_rawDesc), len(file_signature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_signature_proto_goTypes,
		DependencyIndexes: file_signature_proto_depIdxs,
		MessageInfos:      file_signature_proto_msgTypes,
	}.Build()
	File_signature_proto = out.File
	file_signature_proto_goTypes = nil
	file_signature_proto_depIdxs = nil
}
